### PR TITLE
Sort locales by language code

### PR DESCRIPTION
**Pull request by GreenLunar**
I hope I did not break anything

### CODE REVIEW

**Comment by benlangfeld** [comment]
The indenting is inconsistent here. Please follow the tab convention. You'll also need to say *something* to justify the change.

**Comment by GreenLunar** [comment]
Does it look better?

**Comment by benlangfeld** [comment]
You still have not given me any good reason to merge this.

**Comment by GreenLunar** [comment]
Please assist me.  I did sort translations according to language code and indent colons.

**Comment by benlangfeld** [comment]
I understand what you did. I do not really understand why, however. Right now this is a change for the sake of a change. I need some better reason for this to be written down.

**Comment by GreenLunar** [comment]
I did it so frivolous translators would not accidentally translate Candy into a language that is already available, because they thought that the languages are sorted already.

**Comment by linkmauve** [comment]
I think it would be better to have one file per translation, extending the `Candy.View.Translation` object if it already exists (look at other files in the repository for examples), and let the filesystem handle the sorting for you.

Otherwise, if you decide to keep this version, please move the English translation where it should be, there is no reason to have an exception to keep it on top imo.

Also, please rebase your commits together once you are done and ready for a merge.

**Comment by benlangfeld** [comment]
> I think it would be better to have one file per translation

:+1:

**Comment by GreenLunar** [comment]
> I think it would be better to have one file per translation

:+1:

**Comment by GreenLunar** [comment]
See https://github.com/candy-chat/candy/issues/479

**Pull request closed without merging**
