### PR TITLE
Allow links to render correctly in adminMessage and infoMessage

### PR DESCRIPTION
**Pull request by Sudrien**
Currently, messages with links show escaped html

### CODE REVIEW

**Comment by mweibel** [comment]
If I'm not mistaken, this change will lead to XSS issues when those messages contain html. 
Before doing this, you'd need to escape the HTML in there.

**Comment by Sudrien** [comment]
Are you sure? These and standard messages run through Mustache, and the message template has {{{message}}} (line 100, same file).

If this is a problem, I'm not seeing the additional parsing for standard messages.

**Comment by mweibel** [comment]
Yeah but in the message template, the messages are sanitized first (https://github.com/candy-chat/candy/blob/dev/src/view/pane/message.js#L100-103)...

**Comment by Sudrien** [comment]
Still trying to get used to git, been on SVN a long time.

**Comment by mweibel** [comment]
Will verify this patch soon, time's limited at the moment.

**Pull request merged**
