### PR TITLE
avoid to leave room on disconnect

### PR DESCRIPTION
**Pull request by macedo**

### CODE REVIEW

**Comment by benlangfeld** [comment]
@mweibel The point here is that this step is unnecessary, and that it is causing events to fire which trigger related actions (removing room bookmarks) which should not fire on a simple disconnect. Thoughts?

**Comment by bklang** [comment]
I'll add that it is unnecessary because the connection shutting down will automatically make the user leave the rooms. Also, if you have very many rooms open, this process of leaving the rooms can actually be somewhat slow. You can observe this when refreshing or navigating away from a Candy page.

**Comment by mweibel** [comment]
Not sure if I have an opinion here, we had a reason back then when we introduced this (I assume), but this was a long time ago. 
You're sure this doesn't create any regressions?

**Comment by benlangfeld** [comment]
We can't be certain, @mweibel, but it's working fine in our application. We've not found any regressions yet.

**Comment by mweibel** [comment]
Ok, merged now. We'll see after the release if there are regressions :)

**Pull request merged**
