### PR TITLE
Fixed Russian translation and locale settings

### PR DESCRIPTION
**Pull request by MOZGIII**

### CODE REVIEW

**Comment by MOZGIII** [comment]
Did it via github, so no minified builds or other stuff though.

**Comment by mweibel** [comment]
Thanks :) Could you PR against "dev"? dev is our working development branch.

**Comment by MOZGIII** [comment]
Ok, but since I made my changes in master branch of fork, this may be not very clean...

**Comment by MOZGIII** [comment]
It may be easier to cherry-pick the changes.

**Comment by mweibel** [comment]
Ok, I agree :) cherry-picked your changes to dev now. 
Thanks! I'll take care of creating a new release soon.

**Pull request closed without merging**
