### PR TITLE
Allow option to truncate display of long URLs

### PR DESCRIPTION
**Pull request by bklang**

### CODE REVIEW

**Comment by mweibel** [comment]
I don't think it should be truncated by default because if someone sends a malicious URL and room occupants don't see that because the URL arrives truncated. This could have security implications.

**Comment by bklang** [comment]
@mweibel Fixed to not crop URLs by default

**Comment by bklang** [comment]
@mweibel Any more comments on this?

**Comment by mweibel** [comment]
Ok, good :) Intendation seems to be off, but otherwise looks fine :)

**Comment by bklang** [comment]
@mweibel Right, fixed, thanks for catching that :)

**Pull request merged**
