### PR TITLE
just scrolls messages down after rendering the room pane

### PR DESCRIPTION
**Pull request by macedo**

### CODE REVIEW

**Comment by mweibel** [comment]
Could you explain why & why you don't store the scroll position anymore?

**Comment by melissanoelle** [comment]
@mweibel: The problem we were having was that when no chats are opened and you have pending messages coming through from the server (delayed), clicking on the tab to show the chat threw an error that it couldn't find scrollTop of undefined. 

In testing this, I found that if I were to do `Candy.View.Pane.Room.show('madamei@powerhrg.com')` in the console, the chat would show up just fine.

Looking at this:
```
    tabClick: function(e) {
      // remember scroll position of current room
      var currentRoomJid = Candy.View.getCurrent().roomJid;
      self.Chat.rooms[currentRoomJid].scrollPosition = self.Room.getPane(currentRoomJid, '.message-pane-wrapper').scrollTop();

      self.Room.show($(this).attr('data-roomjid'));
      e.preventDefault();
    },
```
What I think is going on is that it's trying to prescroll to the bottom of the current room, but since there is no current room open we can't prescroll to the bottom of it. Notice how it's trying to scroll to the bottom of the `currentRoomJid` before we even `.show()` the new room indicated by the tab? 

@macedo's solution here makes sure that the message pane exists before trying to scroll to the bottom of it--if it doesn't, it doesn't bother to scroll. If it does exist, it behaves as normal.

**Comment by mweibel** [comment]
Ok, thanks for the explanation @melissanoelle and for cleaning up the PR @macedo.

**Comment by donhatch** [comment]
Hi, I'm trying to make sense of the code having to do with the saving and restoring of scrollPosition.

This PR looks suspect to me; it looks to me like before this change, it gets the scroll position
from scrollTop() of the DOM element of class '.message-pane-wrapper', but after this change, it gets it from the DOM element of class '.message-pane' instead (if there is one).
But, both before and after this change, the saved value gets restored to the DOM element of class '.message-pane-wrapper', i.e. after this change it's now saving from one element and restoring to a different one.
So It seems that this change may have broken the saving/restoring mechanism?

Unfortunately I don't have a working testbed to test the effect of this PR, to see what it actually fixed and/or broke; the program I am inspecting seems to be from a fork of candy-chat from some time before this PR (which has different problems having to do with this saving/restoring, which I'm trying to understand).

**Comment by donhatch** [comment]
Note that the problem I just pointed out above is also pointed out in https://github.com/candy-chat/candy/issues/401#issuecomment-137453142 in which https://github.com/amcorona asks for the  '.message-pane' to be changed back to '.message-pane-wrapper'.

**Comment by donhatch** [comment]
Oh, I see.  That requested change is 542649ad95a59210a66f623551b386d6cd9e97f7  which has been submitted to branch origin/feature/401-fix-autoscroll  but not yet submitted to origin/master.

**Comment by donhatch** [comment]
Actually I think I was mistaken: at the time of this change,  the restoring was done into '.message-pane'.   The change in which that was changed to '.message-pane-wrapper' was done a few months later in commit 542649ad95a59210a66f623551b386d6cd9e97f7 .  So maybe this PR is fine, and that later commit is buggy?  Not sure.  In any case, it looks to me like, in the master branch which is at this moment 9ac409e3c1082bf6940b3a0974d6b90b8dcbffdc, the value is saved from .message-pane and restored to .message-pane-wrapper, which looks wrong.

**Pull request merged**
